# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sync.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsync.proto\"`\n\x0cMemoryPacket\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x18\n\x10\x65ncrypted_memory\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x04 \x01(\t\"+\n\x07SyncAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t21\n\x08\x41riaPeer\x12%\n\nSyncMemory\x12\r.MemoryPacket\x1a\x08.SyncAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMORYPACKET']._serialized_start=14
  _globals['_MEMORYPACKET']._serialized_end=110
  _globals['_SYNCACK']._serialized_start=112
  _globals['_SYNCACK']._serialized_end=155
  _globals['_ARIAPEER']._serialized_start=157
  _globals['_ARIAPEER']._serialized_end=206
# @@protoc_insertion_point(module_scope)
