# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sync_pb2 as sync__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sync_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AriaPeerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PerformHandshake = channel.unary_unary(
                '/AriaPeer/PerformHandshake',
                request_serializer=sync__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=sync__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.SyncMemory = channel.unary_unary(
                '/AriaPeer/SyncMemory',
                request_serializer=sync__pb2.SyncMemoryRequest.SerializeToString,
                response_deserializer=sync__pb2.SyncMemoryResponse.FromString,
                _registered_method=True)
        self.SendToDashboard = channel.unary_unary(
                '/AriaPeer/SendToDashboard',
                request_serializer=sync__pb2.DashboardSyncRequest.SerializeToString,
                response_deserializer=sync__pb2.DashboardSyncResponse.FromString,
                _registered_method=True)


class AriaPeerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PerformHandshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendToDashboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AriaPeerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PerformHandshake': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformHandshake,
                    request_deserializer=sync__pb2.HandshakeRequest.FromString,
                    response_serializer=sync__pb2.HandshakeResponse.SerializeToString,
            ),
            'SyncMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncMemory,
                    request_deserializer=sync__pb2.SyncMemoryRequest.FromString,
                    response_serializer=sync__pb2.SyncMemoryResponse.SerializeToString,
            ),
            'SendToDashboard': grpc.unary_unary_rpc_method_handler(
                    servicer.SendToDashboard,
                    request_deserializer=sync__pb2.DashboardSyncRequest.FromString,
                    response_serializer=sync__pb2.DashboardSyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AriaPeer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AriaPeer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AriaPeer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PerformHandshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AriaPeer/PerformHandshake',
            sync__pb2.HandshakeRequest.SerializeToString,
            sync__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AriaPeer/SyncMemory',
            sync__pb2.SyncMemoryRequest.SerializeToString,
            sync__pb2.SyncMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendToDashboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AriaPeer/SendToDashboard',
            sync__pb2.DashboardSyncRequest.SerializeToString,
            sync__pb2.DashboardSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
