# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/sync.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/sync.proto\"O\n\x0bMemoryEntry\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x12\r\n\x05trust\x18\x04 \x01(\t\"0\n\nPluginPush\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61ta_b64\x18\x02 \x01(\t\"\xa7\x01\n\x11SyncMemoryRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x18\n\x10\x65ncrypted_memory\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x12\x18\n\x10\x63urrent_cycle_id\x18\x04 \x01(\t\x12\x16\n\x0e\x61\x63tive_plugins\x18\x05 \x03(\t\x12 \n\x0bplugin_push\x18\x06 \x01(\x0b\x32\x0b.PluginPush\"T\n\x12SyncMemoryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x15\n\rpeer_cycle_id\x18\x02 \x01(\t\x12\x16\n\x0e\x61\x63tive_plugins\x18\x03 \x03(\t\"-\n\x10HandshakeRequest\x12\x19\n\x11sender_public_key\x18\x01 \x01(\x0c\",\n\x11HandshakeResponse\x12\x17\n\x0fpeer_public_key\x18\x01 \x01(\x0c\x32|\n\x08\x41riaPeer\x12\x39\n\x10PerformHandshake\x12\x11.HandshakeRequest\x1a\x12.HandshakeResponse\x12\x35\n\nSyncMemory\x12\x12.SyncMemoryRequest\x1a\x13.SyncMemoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMORYENTRY']._serialized_start=20
  _globals['_MEMORYENTRY']._serialized_end=99
  _globals['_PLUGINPUSH']._serialized_start=101
  _globals['_PLUGINPUSH']._serialized_end=149
  _globals['_SYNCMEMORYREQUEST']._serialized_start=152
  _globals['_SYNCMEMORYREQUEST']._serialized_end=319
  _globals['_SYNCMEMORYRESPONSE']._serialized_start=321
  _globals['_SYNCMEMORYRESPONSE']._serialized_end=405
  _globals['_HANDSHAKEREQUEST']._serialized_start=407
  _globals['_HANDSHAKEREQUEST']._serialized_end=452
  _globals['_HANDSHAKERESPONSE']._serialized_start=454
  _globals['_HANDSHAKERESPONSE']._serialized_end=498
  _globals['_ARIAPEER']._serialized_start=500
  _globals['_ARIAPEER']._serialized_end=624
# @@protoc_insertion_point(module_scope)
