# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sync.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsync.proto\x12\x04sync\"\x85\x01\n\x11SyncMemoryRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x18\n\x10\x65ncrypted_memory\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x12\x18\n\x10\x63urrent_cycle_id\x18\x04 \x01(\t\x12\x16\n\x0e\x61\x63tive_plugins\x18\x05 \x03(\t\"_\n\x07SyncAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rpeer_cycle_id\x18\x03 \x01(\t\x12\x1b\n\x13peer_active_plugins\x18\x04 \x03(\t2@\n\x08\x41riaPeer\x12\x34\n\nSyncMemory\x12\x17.sync.SyncMemoryRequest\x1a\r.sync.SyncAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNCMEMORYREQUEST']._serialized_start=21
  _globals['_SYNCMEMORYREQUEST']._serialized_end=154
  _globals['_SYNCACK']._serialized_start=156
  _globals['_SYNCACK']._serialized_end=251
  _globals['_ARIAPEER']._serialized_start=253
  _globals['_ARIAPEER']._serialized_end=317
# @@protoc_insertion_point(module_scope)
